name: Release Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: tomo-linux
            deps: libncurses5-dev
          - os: macos-latest
            artifact_name: tomo-macos
            deps: ncurses
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            sudo apt-get update
            sudo apt-get install -y ${{ matrix.deps }}
          else
            brew install ${{ matrix.deps }}
          fi

      - name: Build
        run: make

      - name: Package Binary
        run: tar czf ${{ matrix.artifact_name }}.tar.gz build/tomo

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: tomo-linux
          path: .
      - uses: actions/download-artifact@v4
        with:
          name: tomo-macos
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: "tomo-linux.tar.gz,tomo-macos.tar.gz"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
